# permissions for end users to edit configmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmap-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dbkube
    app.kubernetes.io/part-of: dbkube
    app.kubernetes.io/managed-by: kustomize
  name: configmap-editor-role
rules:
- apiGroups:
  - configmaps.etz.com
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configmaps.etz.com
  resources:
  - configmaps/status
  verbs:
  - get
