# permissions for end users to view secrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dbkube
    app.kubernetes.io/part-of: dbkube
    app.kubernetes.io/managed-by: kustomize
  name: secret-viewer-role
rules:
- apiGroups:
  - secrets.etz.com
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.etz.com
  resources:
  - secrets/status
  verbs:
  - get
