apiVersion: deployments.etz.com/v1alpha1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: deployment-sample
    app.kubernetes.io/part-of: dbkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dbkube
  name: deployment-sample
spec:
  # TODO(user): Add fields here
