apiVersion: services.etz.com/v1alpha1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: service-sample
    app.kubernetes.io/part-of: dbkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dbkube
  name: service-sample
spec:
  # TODO(user): Add fields here
